[target.thumbv6m-none-eabi]
rustflags = [
  # Usual Arm bare-metal linker setup
  "-Clink-arg=-Tmemory.x",
  # tell Rust we have a Cortex-M55
  #"-Ctarget-cpu=cortex-m55",
  # tell Rust our Cortex-M55 doesn't have Floating-Point M-Profile Vector
  # Extensions (but it does have everything else a Cortex-M55 could have).
  #"-Ctarget-feature=-mve.fp"
  "--emit=obj"

]

[build]
target = "thumbv6m-none-eabi"